### ISSUE TITLE
TODO Base Core

### ISSUE THREAD

**Issue by JamesParkDev** [JamesParkDev/bitschool-bot#1]
Doing basics:

- [ ] Command handler (Simple)
- [ ] Event handler (Simple)
- [ ] Extend discord.Client for this and store everything in Collection<string, Command|Event>
- [ ] Simple config file with all relative information
- [ ] add eslint, prettier and .gitignore

**Comment by feb199** [comment]
First 4 Completed
